import { Category, Location, Listing, Seller, Profile } from '@/lib/types';

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Café & Coffee', name_ar: 'قهوة ومعدات المقاهي', slug: 'cafe-coffee', icon: 'coffee', sort_order: 1 },
  { id: 'cat-2', name: 'Cuisine chaude', name_ar: 'معدات الطبخ', slug: 'cuisine-chaude', icon: 'flame', sort_order: 2 },
  { id: 'cat-3', name: 'Froid & Réfrigération', name_ar: 'تبريد وتجميد', slug: 'froid-refrigeration', icon: 'snowflake', sort_order: 3 },
  { id: 'cat-4', name: 'Mobilier', name_ar: 'أثاث', slug: 'mobilier', icon: 'chair', sort_order: 4 },
  { id: 'cat-5', name: 'Équipements divers', name_ar: 'معدات متنوعة', slug: 'equipements-divers', icon: 'wrench', sort_order: 5 },
  { id: 'cat-6', name: 'Pâtisserie & Boulangerie', name_ar: 'حلويات ومخابز', slug: 'patisserie-boulangerie', icon: 'croissant', sort_order: 6 },
];

export const DEMO_LOCATIONS: Location[] = [
  { id: 'loc-1', name: 'Tunis', name_ar: 'تونس', slug: 'tunis' },
  { id: 'loc-2', name: 'Ariana', name_ar: 'أريانة', slug: 'ariana' },
  { id: 'loc-3', name: 'Sousse', name_ar: 'سوسة', slug: 'sousse' },
  { id: 'loc-4', name: 'Sfax', name_ar: 'صفاقس', slug: 'sfax' },
  { id: 'loc-5', name: 'Nabeul', name_ar: 'نابل', slug: 'nabeul' },
  { id: 'loc-6', name: 'Bizerte', name_ar: 'بنزرت', slug: 'bizerte' },
  { id: 'loc-7', name: 'Monastir', name_ar: 'المنستير', slug: 'monastir' },
  { id: 'loc-8', name: 'Gabès', name_ar: 'قابس', slug: 'gabes' },
  { id: 'loc-9', name: 'Kairouan', name_ar: 'القيروان', slug: 'kairouan' },
  { id: 'loc-10', name: 'Ben Arous', name_ar: 'بن عروس', slug: 'ben-arous' },
];

export const DEMO_SELLERS: Seller[] = [
  {
    id: 'seller-1',
    full_name: 'Mohamed Ben Ali',
    phone: '98123456',
    email: 'mohamed@example.com',
    management_token: 'seller-token-1',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seller-2',
    full_name: 'Fatma Trabelsi',
    phone: '99887766',
    email: null,
    management_token: 'seller-token-2',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_LISTINGS: Listing[] = [
  {
    id: 'demo-1',
    title: 'Machine à café La Cimbali M27 — 2 groupes',
    description: 'Machine à café professionnelle La Cimbali M27, 2 groupes, en excellent état. Utilisée pendant 3 ans dans un café à Tunis. Entretenue régulièrement. Idéale pour un café ou restaurant de taille moyenne.\n\nCaractéristiques :\n- 2 groupes\n- Chaudière 10L\n- Pompe volumétrique\n- Buse vapeur\n\nPrix négociable pour achat rapide.',
    price: 4500,
    condition: 'occasion',
    category_id: 'cat-1',
    location_id: 'loc-1',
    phone: '98123456',
    seller_name: 'Mohamed',
    seller_id: 'seller-1',
    brand: 'La Cimbali',
    model: 'M27',
    year: 2021,
    energy_type: 'electrique',
    user_id: null,
    management_token: 'demo-token-1',
    status: 'active',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[0],
    location: DEMO_LOCATIONS[0],
    images: [],
    seller: { id: 'seller-1', full_name: 'Mohamed Ben Ali', created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  },
  {
    id: 'demo-2',
    title: 'Four à pizza professionnel à gaz — Double chambre',
    description: 'Four à pizza professionnel à gaz, double chambre. Marque italienne, capacité 8 pizzas. Parfait état de fonctionnement. Vendu cause déménagement.',
    price: 3200,
    condition: 'occasion',
    category_id: 'cat-2',
    location_id: 'loc-3',
    phone: '55678901',
    seller_name: 'Ali',
    seller_id: null,
    brand: null,
    model: null,
    year: null,
    energy_type: 'gaz',
    user_id: null,
    management_token: 'demo-token-2',
    status: 'active',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 29 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[1],
    location: DEMO_LOCATIONS[2],
    images: [],
  },
  {
    id: 'demo-3',
    title: 'Réfrigérateur vitrine vertical 400L — Neuf',
    description: 'Réfrigérateur vitrine vertical 400 litres, neuf, encore sous garantie. Porte vitrée, éclairage LED intérieur. Parfait pour boissons ou pâtisseries.',
    price: 2800,
    condition: 'neuf',
    category_id: 'cat-3',
    location_id: 'loc-4',
    phone: '22345678',
    seller_name: 'Sami',
    seller_id: null,
    brand: 'Liebherr',
    model: 'FKvsl 4113',
    year: 2024,
    energy_type: 'electrique',
    user_id: null,
    management_token: 'demo-token-3',
    status: 'active',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[2],
    location: DEMO_LOCATIONS[3],
    images: [],
  },
  {
    id: 'demo-4',
    title: 'Lot de 20 tables et 80 chaises — Restaurant',
    description: 'Lot complet de mobilier de restaurant : 20 tables carrées en bois massif et 80 chaises assorties. Bon état général, quelques traces d\'usure normales. Idéal pour ouvrir un restaurant.',
    price: 5500,
    condition: 'occasion',
    category_id: 'cat-4',
    location_id: 'loc-1',
    phone: '97111222',
    seller_name: 'Karim',
    seller_id: null,
    brand: null,
    model: null,
    year: null,
    energy_type: null,
    user_id: null,
    management_token: 'demo-token-4',
    status: 'sold',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[3],
    location: DEMO_LOCATIONS[0],
    images: [],
  },
  {
    id: 'demo-5',
    title: 'Moulin à café Santos N°1 — Automatique',
    description: 'Moulin à café Santos numéro 1, automatique, très bon état. Mouture réglable. Utilisé dans une boulangerie pendant 2 ans.',
    price: 800,
    condition: 'occasion',
    category_id: 'cat-1',
    location_id: 'loc-5',
    phone: '54321098',
    seller_name: null,
    seller_id: 'seller-1',
    brand: 'Santos',
    model: 'N°1',
    year: 2022,
    energy_type: 'electrique',
    user_id: null,
    management_token: 'demo-token-5',
    status: 'active',
    created_at: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 29.5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[0],
    location: DEMO_LOCATIONS[4],
    images: [],
    seller: { id: 'seller-1', full_name: 'Mohamed Ben Ali', created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  },
  {
    id: 'demo-6',
    title: 'Pétrin professionnel 40L — Spirale',
    description: 'Pétrin à spirale professionnel, cuve de 40 litres en inox. 2 vitesses. Parfait pour boulangerie ou pâtisserie. Marque européenne.',
    price: null,
    condition: 'occasion',
    category_id: 'cat-6',
    location_id: 'loc-2',
    phone: '99887766',
    seller_name: 'Fatma',
    seller_id: 'seller-2',
    brand: null,
    model: null,
    year: null,
    energy_type: 'electrique',
    user_id: null,
    management_token: 'demo-token-6',
    status: 'active',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[5],
    location: DEMO_LOCATIONS[1],
    images: [],
    seller: { id: 'seller-2', full_name: 'Fatma Trabelsi', created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString() },
  },
  {
    id: 'demo-7',
    title: 'Friteuse double bac professionnelle 2x10L',
    description: 'Friteuse professionnelle double bac, 2x10 litres, électrique. Thermostat réglable. Robinets de vidange. Très bon état.',
    price: 1200,
    condition: 'occasion',
    category_id: 'cat-2',
    location_id: 'loc-6',
    phone: '23456789',
    seller_name: 'Nizar',
    seller_id: null,
    brand: null,
    model: null,
    year: null,
    energy_type: 'electrique',
    user_id: null,
    management_token: 'demo-token-7',
    status: 'active',
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[1],
    location: DEMO_LOCATIONS[5],
    images: [],
  },
  {
    id: 'demo-8',
    title: 'Comptoir réfrigéré vitrine pâtisserie 1.5m',
    description: 'Comptoir réfrigéré vitrine pour pâtisserie, 1.5 mètres. Éclairage LED, 3 étagères. Parfait pour exposer gâteaux et viennoiseries. Occasion en bon état.',
    price: 3800,
    condition: 'occasion',
    category_id: 'cat-3',
    location_id: 'loc-7',
    phone: '50123456',
    seller_name: 'Amine',
    seller_id: null,
    brand: null,
    model: null,
    year: null,
    energy_type: 'electrique',
    user_id: null,
    management_token: 'demo-token-8',
    status: 'active',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: DEMO_CATEGORIES[2],
    location: DEMO_LOCATIONS[6],
    images: [],
  },
];

export const DEMO_PROFILE: Profile = {
  id: 'demo-user-1',
  phone: '98123456',
  full_name: 'Utilisateur Demo',
  avatar_url: null,
  has_seen_tour: false,
  created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
};

export function isDemoMode(): boolean {
  return (
    !process.env.NEXT_PUBLIC_SUPABASE_URL ||
    process.env.NEXT_PUBLIC_SUPABASE_URL === 'your_supabase_url_here'
  );
}
